export const GET_CANDIDATE_ADMINISTER_DATA = 'candidateAdminister/GET_CANDIDATE_ADMINISTER_DATA';
export const SET_CANDIDATE_ADMINISTER_DATA = 'candidateAdminister/SET_CANDIDATE_ADMINISTER_DATA';
export const ADD_CANDIDATE_ADMINISTER_DATA = 'candidateAdminister/ADD_CANDIDATE_ADMINISTER_DATA';